### ISSUE TITLE
Consider sans-io

### ISSUE THREAD

**Issue by k0nserv** [ystreet/librice#28]
Hey @ystreet,

Cool project, always happy to see more Rust in this space. We have had good success in our WebRTC implementation, [str0m](https://github.com/algesten/str0m/), with a sans-IO implementation inspired by [quinn-proto](https://github.com/quinn-rs/quinn/tree/main/quinn-proto).

A sans-IO solution is nice because it doesn't tie the user to a async IO, or even a specific runtime.

**Comment by ystreet** [comment]
sans-IO is something I am definitely considering and would be reasonably happy to accept such a design for this project.
