### ISSUE TITLE
Readme refers to STUN RFC instead of ICE

### ISSUE THREAD

**Issue by nils-ohlmeier** [ystreet/librice#5]
RFC 5389 referred to in your README only defines STUN. But it looks like you actually want to implement ICE. So you should aim to implement RFC 8445 https://tools.ietf.org/html/rfc8445, the latest version of ICE.

**Comment by nils-ohlmeier** [comment]
Happy to provide a PR if it helps.

**Comment by ystreet** [comment]
Ah, yes :).  A PR would be most welcome.

**Comment by ystreet** [comment]
Fixed with https://github.com/ystreet/librice/pull/6
